name: Update
on:
  schedule:
    - cron: "0 6 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    container:
      image: "fedora:latest"
    steps:
      - name: Install dependencies
        run: |
          microdnf -y install git rpm-build curl jq rpmdevtools

      - name: Checkout
        uses: actions/checkout@v4

      - name: git config
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Check for updates
        run: |
          cd yazi
          ./update.sh
